stt:
  model: "base.en" #"moonshine/base"
  language: "en-us"
  beam_size: 2
  vad_filter: true

tts:
  model: "kokoro"
  voice: "bf_alice"
  speed: 1.0
  lang: "en-gb"

llm:
  #model_path: "/home/vsrinivasan/Projects/assistants/models/tinyllama-1.1b-chat-v1.0.Q4_K_M.gguf"
  #model_path: "/home/vsrinivasan/Projects/assistants/models/tinyllama-1.1b-chat-v1.0.Q5_K_M.gguf"
  #model_path: "/home/vsrinivasan/Projects/assistants/models/mistral-7b-instruct-v0.1.Q4_K_M.gguf"
  model_path: "/home/vsrinivasan/Projects/assistants/models/phi-2.Q4_K_M.gguf"
  n_ctx: 512

stream:
  modality: "audio"
  mode: "send-receive"
  can_interrupt: true
  algo_options:
    audio_chunk_duration: 0.6
    started_talking_threshold: 0.1
    speech_threshold: 0.2
  model_options:
    threshold: 0.5
    min_speech_duration_ms: 250
    max_speech_duration_s: 30
    min_silence_duration_ms: 2000
    window_size_samples: 1024
    speech_pad_ms: 400
