stt:
  model: "small.en"

tts:
  model: "kokoro"
  voice: "af_heart"
  speed: 1.0
  lang: "en-us"

llm:
  model_path: "${hydra:runtime.cwd}/models/mistral-7b-instruct-v0.1.Q4_K_M.gguf"
  n_ctx: 512

stream:
  wake_word: "computer"
  modality: "audio"
  mode: "send-receive"
  can_interrupt: true
  algo_options:
    audio_chunk_duration: 0.6
    started_talking_threshold: 0.2
    speech_threshold: 0.1
  model_options:
    threshold: 0.5
    min_speech_duration_ms: 250
    max_speech_duration_s: 30
    min_silence_duration_ms: 2000
    window_size_samples: 1024
    speech_pad_ms: 400
